version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://log_user:log_password@db:5432/log_db"
    networks:
      - app_network
    volumes:
      - ./backend:/app
    command: ["/bin/sh", "-c", "until pg_isready -h db -p 5432; do sleep 2; done && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./frontend:/app  # اتصال کل دایرکتوری frontend
      - /app/node_modules  # جلوگیری از هم‌پوشانی node_modules
    command: ["nginx", "-g", "daemon off;"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: log_db
      POSTGRES_USER: log_user
      POSTGRES_PASSWORD: log_password
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    networks:
      - app_network
    environment:
      PGADMIN_DEFAULT_EMAIL: "samad.elmakchi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "61656165"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
